accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import register

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(), name='login'),
    path('logout/', auth_view.LogoutView.as_view(
        template_name='registration/logout.html'), name='logout'),
    path('register/', register, name='register')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    # 127.0.0.1:8000/abcd/ 로 들어가면 admin 주소에 안결려서 아래로 이동
    path('', include('photo.urls')), # main인데 include 다른 url 주소로 넘겨주는 역할을함

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# debug 모드일때만 활용 가능
# 실제 배포 시
# 1. 미디어 파일 서버를 별도로 두고 사용한다.
# 2. 웹서버에서 별도로 서빙 설정을 한다.

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo
# 2차 url 파일
app_name = 'photo' # name_space

urlpatterns = [
    path('', photo_list, name='photo_list'),
    # 글래스형 뷰가 아니라서 as_view가 안들어감
    # path('detail/<int:pk>/', DetailView.as_view(model=Photo, template_name='photo/detail.html'),
    #      name='photo_detail'),
    path('detail/<int:pk>/', PhotoDetailView.as_view(), name='photo_detail'),
    # view.py에다 써주는게 아니라 여기다 바로 써주는 것, view에다 써줘도 짧은 내용은 그냥 써줘도됨
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    # 어떤 게시글을 delete할지 알아야하기에 int가 붙음
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
]

accounts/models.py
from django.db import models

# Create your models here.

photo/models.py
from django.db import models

# Create your models here.

# 장고의 기본 유저 모델
from django.contrib.auth.models import User
from django.urls import reverse
# models.Model에 장고의 ORM기능이 다 들어 가있어서 필드만 명시해도 기능이 동작함


class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    # on_delete = 유저가 삭제할때 모든 데이터 삭제
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default="photos/no_image.png")
    # 이미지를 년월일 순으로 이미지를 저장하겠다, 기본 값이 없으면 무조건 넣어야하는 것, 예를 들어 게시글을 올리는데 사진 없이 올리는게 불가능하게 하려면 안써도됨
    text = models.TextField()
    # 텍스트필드는 기본값이 없어도 된다.
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # auto_now_add 작성한 시간, auto_now 수정한 시간을 매번 반복

    # 모델 완성 후 = makemigrations 변경사항이 뭐가 있는지 -< migrate 변경사항 저장
    class Meta:
        ordering = ['-updated']
        # 제일 최근에 찍은 사진 순으로 정렬하는 것

    def __str__(self):
        return self.author.username + "" + self.created.strftime("%Y-%m-%d %H:%M:%S")
        # 사진을 작성한 유저의 아이디값을 가져오는 것

    def get_absolute_url(self):
        # 작성이나 수정을 하면 어느 페이지로 읻오하는지
        return reverse('photo:photo_detail', args=[self.id])

accounts/forms.py
from django.contrib.auth.models import User
from django import forms

# 폼은 html에 태그인데 프론트에서 사용자의 입력을 받는 인터페이스
# 장고의 폼 : HTML의 폼 역할, 데이터베이스에 저장할 내용을 형식, 제약조건을 결정하게됨


class RegisterForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput) # 비밀번호, widget의 저 값은 ***나오게하는 것
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput) # 비밀번호 확인

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']
        # 입력 받을 form이 자동으로 생성

    def clean_password2(self):
        cd = self.cleaned_data # sql 인잭션을 해놓은 data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords not matched!')
        return cd['password2']

accounts/views.py
from django.shortcuts import render
from .forms import RegisterForm
# Create your views here.
# CRUD Create, Update = 입력을 받아야하는 것은 html의 form이 필요

# 페이지 그냥 접속시 GET방식 버튼을 누르는 것은 POST
def register(request):
    if request.method == 'POST':
        # 회원 가입 데이터 입력 완료
        user_form = RegisterForm(request.POST)
        if user_form.is_valid(): # 올바르다면 데이터가 다 있다는 뜻
            new_user = user_form.save(commit=False)
            # user 폼의 세이브가 진행되면
            new_user.set_password(user_form.cleaned_data['password'])
            # 원래 폼에서 입력한 패스워드를 패스워드로 저장함
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user':new_user})
            # HTML로 변수를 전할 때 맨 마지막 new_user처럼 넘겨주면됨
    else:
        # 회원 가입 내용을 입력하는 상황
        user_form = RegisterForm()
    return render(request, 'registration/register.html', {'form':user_form})

photo/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Photo
# Create your views here.

@login_required # decorate 기법
def photo_list(request):
    # 함수형 뷰는 항상 첫 번째 매개변수는 request로 넣어줌 req로 해도됨
    # 보여줄 사진 데이터
    photos = Photo.objects.all()
    # objects라는 orm 매니저한테 오브젝트 다 받아 오는 것
    return render(request, 'photo/list.html', {'photos':photos})
    # render 화면에 표시해 주는 것 request가 거의 항상 먼저 들어옴
    # 경로는 templates이 기본 경로로 깔려있음
    # object_list = photos로 바꿀 수 있음


from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect # uploadview에서 필요함


class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo', 'text'] # 작성자(author), 작성시간(created)
    template_name = 'photo/upload.html'

    def form_valid(self, form): # 입력받은 데이터가 올바르다면 저장을하는 함수
        # form 안에는 photo 모델의 인스턴스가 존재하고 입력받을 수 있는 폼을 만들어준다.
        form.instance.author_id = self.request.user.id # fk라 author라는 필드명의 id를 가져온다는 의미
        if form.is_valid():
            # 데이터가 올바르다면 저장
            form.instance.save() # 여기서 인스턴스는 model의 폼팩토리
            return redirect('/')
            # success url이 동작하는 것
        else:
            return self.render_to_response({'form':form})
            # 예를들어 회원가입할때 잘못입력하면 해당 페이지로 다시 가는데 칸이 비어있지않고 입력했던게 채워져있으려면 넣어야함


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/' # main화면
    template_name = 'photo/delete.html'


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/update.html'


class PhotoDetailView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo', 'text']
    template_name = 'photo/detail.html'

photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="alert alert-info">
                Do you want to delete {{object}}?
    <!--            여기서 object는 model에 str 메소드에서 가져옴-->
            </div>
            <form action="" method="post">
    <!--            action 아래 sumit 후 이동하는 페이지 없으면 강은 페이지-->
                {{form.as_p}}
                {% csrf_token %}
    <!--            csrf 공격을 방지 -->
                <input type="submit" class="btn btn-primary" value="Confirm">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <p><img src="{{object.photo.url}}" style="width:100%;"></p>
                <button type="button" class="btn btn-xs btn info">
                    {{object.author.username}}
                </button>
                <p>{{object.text|linebreaksbr}}</p>
            <a href="{% url 'photo:photo_delete' pk=object.id %}"
               class="btn btn-outline-danger btn-sm float-right">Delete</a>
            <a href="{% url 'photo:photo_update' pk=object.id %}"
               class="btn btn-outline-success btn-sm float-right">Update</a>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title %}- List{% endblock %}

{% block content %}
    {% for post in photos %}
        <div class="row">
            <div class="col-md-2"></div>
    <!--        coll-md-2 부트스트렙 문법 너비가 어느정도일때 2블록을 가져간다는 의미 기본 12조각으로 나눔-->
            <div class="col-md-8 panel panel-default"></div>
                <p><img src="{{post.photo.url}}" style="width:100%;"></p>
    <!--        포스트 사진 게시글 중에 하나, 포토 인스턴스 중에 하나 그리고 photo 필드에서 url(경로)를 나타냄-->
                <button type="button" class="btn btn-xs btn info">
                    {{post.author.username}}
                </button>
    <!--        btn info 버튼 색-->
                <p>{{post.text|linebreaksbr}}</p>
    <!--        |뒤가 옵션임 템플릿 필터라고 부름, 게시글에서 엔터 치면 줄바꿈이 되는 것 html에서 줄바꿈은 br인데
                줄바꿈 문자로 바꿔주는 것, 데이터베이스에 들어갈때는 줄바꿈 문자로 들어감-->
                <p class="text-right">
                    <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
                </p>
            <div class="col-md-2"></div>
        </div>
    {% endfor %}

{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}- Update{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">
    <!--            action 아래 sumit 후 이동하는 페이지 없으면 강은 페이지-->
                {{form.as_p}}
                {% csrf_token %}
    <!--            csrf 공격을 방지 -->
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}- Upload{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">
    <!--            action 아래 sumit 후 이동하는 페이지 없으면 강은 페이지-->
                {{form.as_p}}
                {% csrf_token %}
    <!--            csrf 공격을 방지 -->
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <title>Dstagram {% block title %}{% endblock %}</title>
</head>
<body>

<div class="container">
    <header class="header clearfix">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="/">Dstagram</a>
            <ul class="nav">
                <li class="nav-item"><a href="/" class="active nav-link ">Home</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="#" class="nav-link">Welcome, {{user.get_username}}</a></li>
                <li class="nav-item"><a href="{% url 'photo:photo_upload' %}" class="nav-link">Upload</a></li>
                <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Login</a></li>
                <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock %}

    <footer class="footer">
        <p>&copy; 2021 MinWoo. Powered By Django 4</p>
    </footer>
</div>


</body>
</html>